import { Currency } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', flag: '🇺🇸', country: 'United States', iso: 'us' },
  { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺', country: 'Eurozone', iso: 'eu' },
  { code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧', country: 'United Kingdom', iso: 'gb' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵', country: 'Japan', iso: 'jp' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', flag: '🇦🇺', country: 'Australia', iso: 'au' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', flag: '🇨🇦', country: 'Canada', iso: 'ca' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', flag: '🇨🇭', country: 'Switzerland', iso: 'ch' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳', country: 'China', iso: 'cn' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳', country: 'India', iso: 'in' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', flag: '🇧🇷', country: 'Brazil', iso: 'br' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺', country: 'Russia', iso: 'ru' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', flag: '🇰🇷', country: 'South Korea', iso: 'kr' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', flag: '🇲🇽', country: 'Mexico', iso: 'mx' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩', country: 'Indonesia', iso: 'id' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷', country: 'Turkey', iso: 'tr' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: '🇿🇦', country: 'South Africa', iso: 'za' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', flag: '🇭🇰', country: 'Hong Kong', iso: 'hk' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', flag: '🇸🇬', country: 'Singapore', iso: 'sg' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪', country: 'Sweden', iso: 'se' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴', country: 'Norway', iso: 'no' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰', country: 'Denmark', iso: 'dk' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱', country: 'Poland', iso: 'pl' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', flag: '🇹🇭', country: 'Thailand', iso: 'th' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾', country: 'Malaysia', iso: 'my' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭', country: 'Philippines', iso: 'ph' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', flag: '🇻🇳', country: 'Vietnam', iso: 'vn' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', flag: '🇪🇬', country: 'Egypt', iso: 'eg' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬', country: 'Nigeria', iso: 'ng' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', flag: '🇦🇷', country: 'Argentina', iso: 'ar' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', flag: '🇨🇱', country: 'Chile', iso: 'cl' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', flag: '🇨🇴', country: 'Colombia', iso: 'co' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', flag: '🇵🇪', country: 'Peru', iso: 'pe' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦', country: 'Ukraine', iso: 'ua' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿', country: 'Czech Republic', iso: 'cz' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺', country: 'Hungary', iso: 'hu' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', flag: '🇮🇱', country: 'Israel', iso: 'il' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', flag: '🇸🇦', country: 'Saudi Arabia', iso: 'sa' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪', country: 'United Arab Emirates', iso: 'ae' },
  { code: 'QAR', name: 'Qatari Rial', symbol: '﷼', flag: '🇶🇦', country: 'Qatar', iso: 'qa' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', flag: '🇰🇼', country: 'Kuwait', iso: 'kw' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', flag: '🇧🇭', country: 'Bahrain', iso: 'bh' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'RO', flag: '🇴🇲', country: 'Oman', iso: 'om' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', flag: '🇯🇴', country: 'Jordan', iso: 'jo' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', flag: '🇱🇧', country: 'Lebanon', iso: 'lb' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ID', flag: '🇮🇶', country: 'Iraq', iso: 'iq' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷', country: 'Iran', iso: 'ir' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰', country: 'Pakistan', iso: 'pk' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩', country: 'Bangladesh', iso: 'bd' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰', country: 'Sri Lanka', iso: 'lk' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲', country: 'Myanmar', iso: 'mm' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭', country: 'Cambodia', iso: 'kh' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', flag: '🇱🇦', country: 'Laos', iso: 'la' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳', country: 'Mongolia', iso: 'mn' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'so\'m', flag: '🇺🇿', country: 'Uzbekistan', iso: 'uz' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿', country: 'Kazakhstan', iso: 'kz' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', flag: '🇬🇪', country: 'Georgia', iso: 'ge' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', flag: '🇦🇲', country: 'Armenia', iso: 'am' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿', country: 'Azerbaijan', iso: 'az' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾', country: 'Belarus', iso: 'by' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩', country: 'Moldova', iso: 'md' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'din', flag: '🇷🇸', country: 'Serbia', iso: 'rs' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', flag: '🇦🇱', country: 'Albania', iso: 'al' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'den', flag: '🇲🇰', country: 'North Macedonia', iso: 'mk' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Mark', symbol: 'KM', flag: '🇧🇦', country: 'Bosnia and Herzegovina', iso: 'ba' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', flag: '🇮🇸', country: 'Iceland', iso: 'is' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪', country: 'Kenya', iso: 'ke' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', flag: '🇺🇬', country: 'Uganda', iso: 'ug' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', flag: '🇹🇿', country: 'Tanzania', iso: 'tz' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹', country: 'Ethiopia', iso: 'et' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', flag: '🇬🇭', country: 'Ghana', iso: 'gh' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', flag: '🇨🇲', country: 'Central Africa', iso: 'cm' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', flag: '🇸🇳', country: 'West Africa', iso: 'sn' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺', country: 'Mauritius', iso: 'mu' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿', country: 'Mozambique', iso: 'mz' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', flag: '🇦🇴', country: 'Angola', iso: 'ao' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲', country: 'Zambia', iso: 'zm' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', flag: '🇧🇼', country: 'Botswana', iso: 'bw' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', flag: '🇳🇦', country: 'Namibia', iso: 'na' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', flag: '🇸🇿', country: 'Eswatini', iso: 'sz' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', flag: '🇱🇸', country: 'Lesotho', iso: 'ls' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', flag: '🇸🇨', country: 'Seychelles', iso: 'sc' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', flag: '🇲🇬', country: 'Madagascar', iso: 'mg' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', flag: '🇲🇼', country: 'Malawi', iso: 'mw' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', flag: '🇷🇼', country: 'Rwanda', iso: 'rw' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', flag: '🇧🇮', country: 'Burundi', iso: 'bi' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', flag: '🇩🇯', country: 'Djibouti', iso: 'dj' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', flag: '🇸🇴', country: 'Somalia', iso: 'so' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: '£SD', flag: '🇸🇩', country: 'Sudan', iso: 'sd' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', flag: '🇹🇳', country: 'Tunisia', iso: 'tn' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'DH', flag: '🇲🇦', country: 'Morocco', iso: 'ma' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', flag: '🇱🇾', country: 'Libya', iso: 'ly' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DA', flag: '🇩🇿', country: 'Algeria', iso: 'dz' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', flag: '🇲🇷', country: 'Mauritania', iso: 'mr' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', flag: '🇨🇻', country: 'Cape Verde', iso: 'cv' },
  { code: 'STD', name: 'Sao Tome and Principe Dobra', symbol: 'Db', flag: '🇸🇹', country: 'Sao Tome and Principe', iso: 'st' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', flag: '🇬🇳', country: 'Guinea', iso: 'gn' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', flag: '🇸🇱', country: 'Sierra Leone', iso: 'sl' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', flag: '🇱🇷', country: 'Liberia', iso: 'lr' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', flag: '🇬🇲', country: 'Gambia', iso: 'gm' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'P', flag: '🇲🇴', country: 'Macau', iso: 'mo' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', flag: '🇹🇼', country: 'Taiwan', iso: 'tw' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', flag: '🇫🇯', country: 'Fiji', iso: 'fj' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬', country: 'Papua New Guinea', iso: 'pg' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', flag: '🇸🇧', country: 'Solomon Islands', iso: 'sb' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', flag: '🇻🇺', country: 'Vanuatu', iso: 'vu' },
  { code: 'TOP', name: 'Tongan Pa\'anga', symbol: 'T$', flag: '🇹🇴', country: 'Tonga', iso: 'to' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', flag: '🇼🇸', country: 'Samoa', iso: 'ws' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', flag: '🇵🇫', country: 'French Polynesia', iso: 'pf' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', flag: '🇧🇧', country: 'Barbados', iso: 'bb' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: '$', flag: '🇯🇲', country: 'Jamaica', iso: 'jm' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: '$', flag: '🇹🇹', country: 'Trinidad and Tobago', iso: 'tt' },
  { code: 'BZD', name: 'Belize Dollar', symbol: '$', flag: '🇧🇿', country: 'Belize', iso: 'bz' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', flag: '🇬🇾', country: 'Guyana', iso: 'gy' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', flag: '🇸🇷', country: 'Suriname', iso: 'sr' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', flag: '🇧🇸', country: 'Bahamas', iso: 'bs' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', flag: '🇰🇾', country: 'Cayman Islands', iso: 'ky' },
  { code: 'BBM', name: 'Bermudian Dollar', symbol: '$', flag: '🇧🇲', country: 'Bermuda', iso: 'bm' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', flag: '🇦🇼', country: 'Aruba', iso: 'aw' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', flag: '🇨🇼', country: 'Curacao', iso: 'cw' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', flag: '🇱🇨', country: 'East Caribbean', iso: 'lc' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', flag: '🇭🇹', country: 'Haiti', iso: 'ht' },
  { code: 'DOP', name: 'Dominican Peso', symbol: '$', flag: '🇩🇴', country: 'Dominican Republic', iso: 'do' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', flag: '🇨🇺', country: 'Cuba', iso: 'cu' },
  { code: 'CRC', name: 'Costa Rican Colon', symbol: '₡', flag: '🇨🇷', country: 'Costa Rica', iso: 'cr' },
  { code: 'NIO', name: 'Nicaraguan Cordoba', symbol: 'C$', flag: '🇳🇮', country: 'Nicaragua', iso: 'ni' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳', country: 'Honduras', iso: 'hn' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹', country: 'Guatemala', iso: 'gt' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾', country: 'Paraguay', iso: 'py' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$', flag: '🇺🇾', country: 'Uruguay', iso: 'uy' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', flag: '🇧🇴', country: 'Bolivia', iso: 'bo' },
];
