import { CountryData } from './types';

export const lifestyleData: CountryData[] = [
  {
    id: 'usa',
    name: 'United States',
    code: 'US',
    costLivingIndex: 100,
    rentIndex: 100,
    groceriesIndex: 100,
    restaurantIndex: 100,
    localPurchasingPowerIndex: 100,
    currency: 'USD',
    currencySymbol: '$',
    exchangeRate: 1,
    lat: 37.0902,
    lng: -95.7129
  },
  {
    id: 'portugal',
    name: 'Portugal',
    code: 'PT',
    costLivingIndex: 43.1,
    rentIndex: 26.5,
    groceriesIndex: 35.8,
    restaurantIndex: 37.2,
    localPurchasingPowerIndex: 40.5,
    currency: 'EUR',
    currencySymbol: '€',
    exchangeRate: 0.92,
    lat: 39.3999,
    lng: -8.2245
  },
  {
    id: 'spain',
    name: 'Spain',
    code: 'ES',
    costLivingIndex: 48.7,
    rentIndex: 23.4,
    groceriesIndex: 40.2,
    restaurantIndex: 45.6,
    localPurchasingPowerIndex: 65.4,
    currency: 'EUR',
    currencySymbol: '€',
    exchangeRate: 0.92,
    lat: 40.4637,
    lng: -3.7492
  },
  {
    id: 'mexico',
    name: 'Mexico',
    code: 'MX',
    costLivingIndex: 32.4,
    rentIndex: 12.8,
    groceriesIndex: 31.5,
    restaurantIndex: 28.4,
    localPurchasingPowerIndex: 38.2,
    currency: 'MXN',
    currencySymbol: '$',
    exchangeRate: 17.5,
    lat: 23.6345,
    lng: -102.5528
  },
  {
    id: 'thailand',
    name: 'Thailand',
    code: 'TH',
    costLivingIndex: 29.6,
    rentIndex: 15.4,
    groceriesIndex: 30.5,
    restaurantIndex: 14.8,
    localPurchasingPowerIndex: 32.1,
    currency: 'THB',
    currencySymbol: '฿',
    exchangeRate: 36.5,
    lat: 15.87,
    lng: 100.9925
  },
  {
    id: 'colombia',
    name: 'Colombia',
    code: 'CO',
    costLivingIndex: 22.8,
    rentIndex: 7.5,
    groceriesIndex: 21.4,
    restaurantIndex: 18.2,
    localPurchasingPowerIndex: 24.5,
    currency: 'COP',
    currencySymbol: '$',
    exchangeRate: 3950,
    lat: 4.5709,
    lng: -74.2973
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    code: 'VN',
    costLivingIndex: 24.5,
    rentIndex: 10.2,
    groceriesIndex: 28.4,
    restaurantIndex: 12.5,
    localPurchasingPowerIndex: 22.1,
    currency: 'VND',
    currencySymbol: '₫',
    exchangeRate: 25400,
    lat: 14.0583,
    lng: 108.2772
  },
  {
    id: 'greece',
    name: 'Greece',
    code: 'GR',
    costLivingIndex: 45.2,
    rentIndex: 15.8,
    groceriesIndex: 38.5,
    restaurantIndex: 42.1,
    localPurchasingPowerIndex: 35.4,
    currency: 'EUR',
    currencySymbol: '€',
    exchangeRate: 0.92,
    lat: 39.0742,
    lng: 21.8243
  },
  {
    id: 'bali',
    name: 'Indonesia (Bali)',
    code: 'ID',
    costLivingIndex: 28.4,
    rentIndex: 18.5,
    groceriesIndex: 32.1,
    restaurantIndex: 15.4,
    localPurchasingPowerIndex: 18.5,
    currency: 'IDR',
    currencySymbol: 'Rp',
    exchangeRate: 16200,
    lat: -8.4095,
    lng: 115.1889
  },
  {
    id: 'albania',
    name: 'Albania',
    code: 'AL',
    costLivingIndex: 31.5,
    rentIndex: 11.2,
    groceriesIndex: 30.1,
    restaurantIndex: 25.4,
    localPurchasingPowerIndex: 28.5,
    currency: 'ALL',
    currencySymbol: 'L',
    exchangeRate: 94.5,
    lat: 41.1533,
    lng: 20.1683
  }
];
